<#
.SYNOPSIS
    Writes .compliance-audit.yml at the repo root - the canonical producer
    paired with ConvertFrom-ComplianceConfig.ps1. Called by the interactive
    Compliance Audit User Gate (Phase B) after standard confirmation.

.DESCRIPTION
    Emits the flat, fixed schema defined in compliance-audit.md (section
    "Config file contract") with a stable standard order:
    canadian_data_sovereignty, pipeda, soc2, iso_27001, hipaa, gdpr.
    Stamps last_confirmed with today's date (ISO yyyy-MM-dd).

    Validation:
      - every standard marked not_applicable in -Decisions MUST have a
        matching entry in -Rationales (throws otherwise)
      - decision values must be required or not_applicable

    -Merge: reads the existing config via ConvertFrom-ComplianceConfig.ps1;
    standards absent from -Decisions keep their existing status/rationale,
    standards present in -Decisions are overwritten, and last_confirmed is
    always refreshed. Without -Merge the file is overwritten.

    Idempotent: writing the same decisions twice yields equivalent files
    (stable ordering, deterministic output).

.PARAMETER RepoRoot
    Repo root where .compliance-audit.yml is written. Default ".".
.PARAMETER TargetRepo
    Leaf name of the repo this config governs (target_repo field). Required.
.PARAMETER Decisions
    Hashtable standard -> required|not_applicable (e.g.
    @{ canadian_data_sovereignty='required'; hipaa='not_applicable' }).
.PARAMETER Rationales
    Hashtable standard -> rationale string. REQUIRED for every
    not_applicable decision.
.PARAMETER RegionRequired
    Region the data-sovereignty check enforces. Default ca-central-1.
.PARAMETER RunNativeEngine
    run_native_engine value (default true).
.PARAMETER ReconfirmAfterDays
    reconfirm_after_days value (default 365).
.PARAMETER Merge
    Merge into an existing config instead of overwriting.

.EXAMPLE
    $d = @{ canadian_data_sovereignty='required'; pipeda='required'; soc2='required';
            iso_27001='required'; hipaa='not_applicable'; gdpr='not_applicable' }
    .\Write-ComplianceAuditConfig.ps1 -RepoRoot C:/repos/demo -TargetRepo demo `
        -Decisions $d -Rationales @{ hipaa='no PHI'; gdpr='no EU data subjects' }
.NOTES
    Output must round-trip through ConvertFrom-ComplianceConfig.ps1 with
    identical decisions/statuses/rationales.
#>

[CmdletBinding()]
param(
    [string]$RepoRoot = ".",
    [Parameter(Mandatory)][string]$TargetRepo,
    [hashtable]$Decisions = @{},
    [hashtable]$Rationales = @{},
    [string]$RegionRequired = "ca-central-1",
    [switch]$RunNativeEngine = $true,
    [int]$ReconfirmAfterDays = 365,
    [switch]$Merge
)

$ErrorActionPreference = "Stop"

$standardOrder = @('canadian_data_sovereignty', 'pipeda', 'soc2', 'iso_27001', 'hipaa', 'gdpr')
$allowedStatus = @('required', 'not_applicable')

$root = (Resolve-Path $RepoRoot -ErrorAction Stop).Path
$outPath = Join-Path $root ".compliance-audit.yml"

# ---- Validate decisions ----
foreach ($key in $Decisions.Keys) {
    if ($standardOrder -notcontains $key) {
        throw "Write-ComplianceAuditConfig: unknown standard '$key' (expected one of $($standardOrder -join ', '))"
    }
    if ($allowedStatus -notcontains $Decisions[$key]) {
        throw "Write-ComplianceAuditConfig: invalid decision '$($Decisions[$key])' for $key (expected required|not_applicable)"
    }
    if ($Decisions[$key] -eq 'not_applicable' -and [string]::IsNullOrWhiteSpace(($Rationales[$key]))) {
        throw "Write-ComplianceAuditConfig: $key marked not_applicable but has no -Rationales entry"
    }
}

# ---- Merge prior state ----
$existingStandards = @{}
if ($Merge -and (Test-Path -LiteralPath $outPath -PathType Leaf)) {
    $existing = & (Join-Path $PSScriptRoot "ConvertFrom-ComplianceConfig.ps1") -Path $outPath
    foreach ($ks in $standardOrder) {
        $existingStandards[$ks] = @{
            status    = $existing.standards[$ks].status
            rationale = $existing.standards[$ks].rationale
        }
    }
}

# ---- Compute final per-standard state ----
$final = @{}
foreach ($ks in $standardOrder) {
    if ($Decisions.ContainsKey($ks)) {
        $final[$ks] = @{
            status    = $Decisions[$ks]
            rationale = if ($Rationales.ContainsKey($ks)) { $Rationales[$ks] } else { '' }
        }
    } elseif ($existingStandards.ContainsKey($ks)) {
        $final[$ks] = $existingStandards[$ks]
    } else {
        $final[$ks] = @{ status = 'required'; rationale = '' }
    }
}

$today = Get-Date -Format "yyyy-MM-dd"

# ---- Emit YAML (hand-rolled; fixed flat schema) ----
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# .compliance-audit.yml - generated by interactive Compliance Audit")
$lines.Add("version: 1")
$lines.Add("target_repo: $TargetRepo")
$lines.Add("region_required: $RegionRequired")
$lines.Add("standards:")
foreach ($ks in $standardOrder) {
    $lines.Add("  ${ks}:")
    $lines.Add("    status: $($final[$ks].status)")
    $rationale = $final[$ks].rationale
    if (-not [string]::IsNullOrWhiteSpace($rationale)) {
        $escaped = $rationale.Replace('"', '\"')
        $lines.Add("    rationale: `"$escaped`"")
    }
}
$lines.Add("run_native_engine: $(if ($RunNativeEngine) { 'true' } else { 'false' })")
$lines.Add("last_confirmed: $today")
$lines.Add("reconfirm_after_days: $ReconfirmAfterDays")

$lines -join "`r`n" | Set-Content -LiteralPath $outPath -Encoding utf8 -NoNewline
Write-Host "Wrote $outPath (last_confirmed: $today)"
