<#
.SYNOPSIS
    Generates fleet alias script with docker exec shortcuts for each agent.
    .DESCRIPTION
    Queries running containers and services, writes a .fleet-aliases.ps1 script
    with named aliases (e.g. Enter-BASE) for easy docker exec access.
.PARAMETER StackName
    The Docker Swarm stack name used to scope container lookups.
.OUTPUTS
    None. Writes .fleet-aliases.ps1 to ~/.ORCHESTRATOR/.
#>
function New-FleetAliases {
    [OutputType([void])]
    param(
        [string]$StackName
    )
Write-SetupLog "Phase 7: Generating fleet aliases"
Write-Information -MessageData "`n[FleetAliases] Generating fleet aliases..." -Tags "WARN"

$AliasDir = Join-Path (Get-HomeDir) ".ORCHESTRATOR"
$AliasFile = Join-Path $AliasDir ".fleet-aliases.ps1"
if (-not (Test-Path $AliasDir)) {
    New-Item -ItemType Directory -Path $AliasDir -Force | Out-Null
}

Start-Sleep -Seconds (Get-InterclawConstants).PostCleanupWaitSec

$ContainerLines = docker ps --filter "name=oc-" --format "{{.ID}}|{{.Names}}" 2>$null
$ServiceLines = docker service ls --format "{{.Name}}" 2>$null

$AliasLines = [System.Collections.Generic.List[string]]::new()
$AliasLines.Add("# Fleet aliases for $StackName stack (generated by 1Deploy.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss'))")
$AliasLines.Add("# Dot-source in your PowerShell profile for auto-loading:")
$AliasLines.Add("#   if (Test-Path ~/.ORCHESTRATOR/.fleet-aliases.ps1) { . ~/.ORCHESTRATOR/.fleet-aliases.ps1 }")
$AliasLines.Add("")
$AliasLines.Add("# Agent exec shortcuts (dynamic container ID lookup)")
$AliasLines.Add("# Usage: base <cmd>  ->  docker exec -it <BASE-container> <cmd>")

$RoleMap = @{}
foreach ($Line in $ContainerLines) {
    if ([string]::IsNullOrWhiteSpace($Line)) { continue }
    $Parts = $Line -split '\|'
    $ContainerId = $Parts[0]
    $ContainerName = $Parts[1]
    if ($ContainerName -match 'oc-base(?:-(\d+))?') {
        $RoleCaption = "BASE"
        $RoleIndex = $Matches[1]
        $suffix = if ($RoleIndex) { "-${RoleIndex}" } else { "" }
        $RoleLower = $RoleCaption.ToLower()
        $RoleMap[$RoleCaption] = @{ ContainerId = $ContainerId; Index = $RoleIndex; ServiceName = "$StackName`_oc-${RoleLower}${suffix}" }
        $AliasLines.Add("function global:${RoleLower}${suffix} { docker exec -it (docker ps --filter `"name=oc-${RoleLower}`" --format `"{{.ID}}`" | Select-Object -First 1) @args }")
        if ($RoleIndex) {
            $AliasLines.Add("function global:${RoleLower}-${RoleIndex} { docker exec -it $ContainerId @args }")
        }
    }
    elseif ($ContainerName -match 'code-(\d+)') {
        $CodeId = $Matches[1]
        $AliasLines.Add("function global:go$CodeId { docker exec -it $ContainerId @args }")
        $AliasLines.Add("function global:code-$CodeId { docker exec -it $ContainerId @args }")
    }
}

$AliasLines.Add("")
$AliasLines.Add("# Service control (Swarm-safe: stop, start, restart, scale)")
$AliasLines.Add('function global:oc-restart { $s = docker service ls --format ''{{.Name}}'' | Where-Object { $_ -match $args[0] } | Select-Object -First 1; if ($s) { docker service update --force $s } else { Write-Information -MessageData "No service matching ''$args[0]''" -Tags "ERROR" } }')
$AliasLines.Add('function global:oc-stop { $s = docker service ls --format ''{{.Name}}'' | Where-Object { $_ -match $args[0] } | Select-Object -First 1; if ($s) { docker service scale "$($s)=0" } else { Write-Information -MessageData "No service matching ''$args[0]''" -Tags "ERROR" } }')
$AliasLines.Add('function global:oc-start { $s = docker service ls --format ''{{.Name}}'' | Where-Object { $_ -match $args[0] } | Select-Object -First 1; if ($s) { docker service scale "$($s)=1" } else { Write-Information -MessageData "No service matching ''$args[0]''" -Tags "ERROR" } }')
$AliasLines.Add("function global:oc-scale { docker service scale `$args[0] }")
$AliasLines.Add("function global:oc-status { docker stack services '$StackName' }")
$AliasLines.Add("function global:oc-ps { docker stack ps '$StackName' }")
$AliasLines.Add("function global:oc-services { docker service ls --filter `"name=${script:StackName}_`" }")

$AliasLines.Add("")
$AliasLines.Add("# Fleet metadata - intentional global scope: these variables are exported to the")
$AliasLines.Add("# user's interactive session when the alias script is dot-sourced, not used as")
$AliasLines.Add("# cross-module state. `$script: scope inside the generated script would be lost")
$AliasLines.Add("# on dot-source completion.")
$AliasLines.Add("`$env:ORCHESTRATOR_FLEET_PROJECT = '$ProjectCode'")
$AliasLines.Add("`$env:ORCHESTRATOR_FLEET_STACK = '$StackName'")
$AliasLines.Add("`$env:ORCHESTRATOR_FLEET_TIER = '$SovereigntyTier'")

# Add custom names if provided
foreach ($Ac in $AgentConfigs) {
    if ($Ac.CustomName) {
        $RoleLower = $Ac.Role.ToLower()
        $AliasLines.Add("`$global:${RoleLower}Name = '$($Ac.CustomName)'")
    }
}

Write-AtomicFile -Path $AliasFile -Value ($AliasLines -join "`n") -Encoding UTF8
Write-Information -MessageData "  [OK] Fleet aliases written to: $AliasFile" -Tags "INFO"
Write-Information -MessageData "  Add to your PowerShell profile for auto-loading:" -Tags "INFO"
Write-Information -MessageData "    if (Test-Path ~/.ORCHESTRATOR/.fleet-aliases.ps1) { . ~/.ORCHESTRATOR/.fleet-aliases.ps1 }" -Tags "INFO"

Write-Information -MessageData "`n[COMPLETED] Fleet of $($AgentConfigs.Count) agent(s) for Project $ProjectCode has been provisioned." -Tags "INFO"

}

