<#
.SYNOPSIS
    Fleet deployment script. Handles parallel image builds, volume seeding, compose generation, Docker Swarm stack deploy, and health verification.
.DESCRIPTION
    Orchestrates the full deployment lifecycle: builds container images in parallel, seeds
    agent config and persistence volumes, generates docker-compose.interclaw.yml, deploys
    the Docker Swarm stack, and verifies fleet health. Supports individual phases for
    targeted re-runs.
.PARAMETER TargetDir
    Repository root directory containing Skills/, Infrastructure/, and install.json.
    Required.
.PARAMETER AgentConfigs
    Array of agent configuration hashtables with Role, Index, InstanceId, AgentName, Port.
    Generated by Resolve-AgentConfigsFromInstallJson.
.PARAMETER ProjectCode
    Three-letter project code (e.g., FRAD). Used for stack and resource naming.
.PARAMETER InstallTailscale
    Whether to include Tailscale in the deployment. "true" or "false".
.PARAMETER InstallFleet
    Whether to deploy the is-fleet container. "true" or "false".
.PARAMETER SovereigntyTier
    Data sovereignty tier: "global", "canada", or "usa". Defaults to "global".
.PARAMETER InstallWorkspaceRepos
    Semicolon-separated list of workspace repository URLs to clone into agent volumes.
.PARAMETER InstallBookkeeping
    Whether to deploy the is-bookkeeping container. "true" or "false".
.PARAMETER Phase
    Deployment phase. Supported: All, Images, Volumes, Swarm, Compose, Deploy, Verify, Aliases.
    "All" runs the full deployment pipeline.
.EXAMPLE
    .\1Deploy.ps1 -TargetDir $RepoRoot -AgentConfigs $configs -ProjectCode FRAD -Phase All
    Run full fleet deployment.
.EXAMPLE
    .\1Deploy.ps1 -TargetDir $RepoRoot -AgentConfigs $configs -ProjectCode FRAD -Phase Images
    Build all container images without deploying.
.NOTES
    File: 1Deploy.ps1
    Requires: PowerShell 7.0+, Docker Desktop with Swarm mode, AWS SSO profile
    See-also: deploy.ps1, 1Provision.ps1, 1Fleet.ps1
#
# Credential scope by phase (R=Read, W=Write, RW=ReadWrite):
# Phase   | Scope
# --------|------------------------------------------
# Images  | Docker API (no credentials)
# Volumes | Docker API (no credentials)
# Compose | No credentials
# Deploy  | ReadWrite AWS SM (proxy/web/Bookkeeper bundles), Docker API
# Verify  | No credentials
#
# Deploy-owned keys (hydrated from AWS SM): ATTIO_READ_KEY, BROWSERLESS_API_KEY,
# proxy bundle (20+ keys), Bookkeeper bundle, fleet bundle (GITHUB_TOKEN_READALL),
# fleet API tokens, Zoho vars, DocuSign SMTP vars.
#>
# ==============================================================================
# Interclaw — DEPLOY ORCHESTRATOR (v19.0 - Deploy Orchestrator (merged from 1Docker.ps1))
# ==============================================================================
# Deploys the Docker Swarm stack using dynamic compose generation based on
# agent count and roles. pulls the official Interclaw image from GHCR, seeds
# config volumes (read-only) and persistence volumes (writable), and generates
# docker-compose.interclaw.yml per run.
# ==============================================================================
param(
    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$TargetDir,

    [Parameter(Mandatory = $true)]
    [ValidateNotNull()]
    [hashtable[]]$AgentConfigs,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[A-Za-z0-9_-]{2,8}$')]
    [string]$ProjectCode,

    [ValidateSet("true","false")]
    [string]$InstallTailscale = "true",
    [ValidateSet("true","false")]
    [string]$InstallFleet = "true",
    [ValidateSet("global","canada","usa")]
    [string]$SovereigntyTier = "global",
    [string]$InstallWorkspaceRepos = "",
    [ValidateSet("true","false")]
    [string]$InstallBookkeeping = "false",
    [ValidateSet("true","false")]
    [string]$InstallMarketer = "false",

    [ValidateSet("All","Images","Volumes","Swarm","Compose","Deploy","Verify","Aliases")]
    [string]$Phase = "All"
)

$ErrorActionPreference = "Stop"

# Bootstrap: load Core module directly so Import-InterclawModule is available
$__ocRepoRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$__dockerModulesDir = "$__ocRepoRoot\Skills\Docker\Modules"
$__salmonModulesDir = "$__ocRepoRoot\Orchestrator\Modules"
$env:PSModulePath = "$__dockerModulesDir;$__salmonModulesDir;$env:PSModulePath"
Initialize-InterclawEnvironment -RepoRoot $__ocRepoRoot

Import-InterclawModule Core
Import-InterclawModule Secrets
Import-InterclawModule Identity
Import-InterclawModule Config
Import-InterclawModule Fleet
Import-InterclawModule Deploy

# Hydrate deploy-specific production secrets
$owns = Get-SecretsOwnedKeys -List Deploy
if ($null -ne $owns -and $owns.Count -gt 0) {
    Import-SecretsFromAws -Keys $owns -SourceLabel "Deploy"
}

Write-SetupLog "1Deploy started ($($AgentConfigs.Count) agents)"

Write-Information -MessageData "`n  ORCHESTRATOR - Docker Fleet Provisioner" -Tags "INFO"

try { $script:StackName = Get-StackName } catch { Write-SetupLog "Get-StackName failed: $_ — defaulting to ProjectCode"; $script:StackName = $ProjectCode }

Write-Information -MessageData "  Project:           $ProjectCode" -Tags "INFO"
Write-Information -MessageData "  Stack Name:        $script:StackName" -Tags "INFO"
Write-Information -MessageData "  Agents:            $($AgentConfigs.Count)" -Tags "INFO"
foreach ($Ac in $AgentConfigs) {
    Write-Information -MessageData "    - $($Ac.AgentName) (role=$($Ac.Role), index=$($Ac.Index), instance=$($Ac.InstanceId), port=$(Get-AgentHostPort -Role $Ac.Role -Index $Ac.Index))" -Tags "INFO"
}

$script:ImageVersion = "local"
$script:PreviousComposeProfiles = $env:COMPOSE_PROFILES

# Propagate deploy toggles to script scope so module functions (Publish-FleetStack,
# Generate-FleetCompose, etc.) can access them consistently.
$script:InstallTailscale   = if ($InstallTailscale)   { $InstallTailscale }   else { "false" }
$script:InstallFleet       = if ($InstallFleet)       { $InstallFleet }       else { "false" }
$script:InstallWorkspaceRepos = if ($InstallWorkspaceRepos) { $InstallWorkspaceRepos } else { "" }

$script:SovereigntyTier    = if ($SovereigntyTier)    { $SovereigntyTier }    else { "global" }

# Expose parameters to script scope so sub-functions (e.g., Publish-FleetStack) can fall back consistently
$script:ProjectCode   = $ProjectCode
$script:AgentConfigs  = $AgentConfigs
$script:InstallBookkeeping = $InstallBookkeeping
$script:InstallMarketer = $InstallMarketer

# ==============================================================================
# PHASE SELECTOR
# ==============================================================================
switch ($Phase) {
    "Images" {
        Write-Information -MessageData "`n[ImageBuild] Starting parallel image builds..." -Tags "INFO"
        $buildCtx = Start-ParallelImageBuild -TargetDir $TargetDir
        $buildResult = Receive-ParallelImageBuild -BuildContext $buildCtx
        if ($null -eq $buildResult -or -not $buildResult.Success) {
            $failed = $buildResult.FailedBuilds -join ", "
            Write-Information -MessageData "  [FAIL] Builds failed: $failed" -Tags "ERROR"
            Write-Information -MessageData "  Logs in: $($buildCtx.BuildLogDir)" -Tags "WARN"
            exit 1
        }
        Write-Information -MessageData "  [OK] All images built successfully." -Tags "INFO"
    }
    "Volumes" {
        $volumeTimeoutSec = 600
        # Volume name conflict check: warn if any expected volume already exists
        # Names follow the deploy pipeline convention (${StackName}_agent_{config,persist}_${svcName}).
        $resolvedStackName = if ($script:StackName) { $script:StackName } else { try { Get-StackName } catch { $ProjectCode } }
        $expectedVolumes = @($AgentConfigs | ForEach-Object {
            $svcName = Get-AgentServiceName -Role $_.Role -Index $_.Index
            "${resolvedStackName}_agent_config_${svcName}"
            "${resolvedStackName}_agent_persist_${svcName}"
        })
        $existingVols = @()
        foreach ($volName in $expectedVolumes) {
            try {
                $volCheck = docker volume ls -q -f "name=^${volName}$" 2>$null
            } catch {
                $volCheck = $null
                Write-SetupLog "Volume existence check failed for ${volName}: $_" -Level WARN
            }
            if ($volCheck) { $existingVols += $volName }
        }
        if ($existingVols.Count -gt 0) {
            Write-SetupLog "Volume conflict check: $($existingVols.Count) pre-existing volume(s) found — $($existingVols -join ', ')" -Level WARN
            Write-Information -MessageData "  [WARN] $($existingVols.Count) expected volume(s) already exist: $($existingVols -join ', ')" -Tags "WARN"
        }
        $volumeJob = Start-Job -Name "InitializeAgentVolumes" -ScriptBlock {
            param($wr, $sn, $st, $ac, $td)
            $modulesDir = Join-Path $td "Skills" "Docker" "Modules"; $env:PSModulePath = "$modulesDir;$env:PSModulePath"
            Import-Module -Name (Join-Path $modulesDir "SalmonRun.ModuleLoader" "SalmonRun.ModuleLoader.psd1") -Force -DisableNameChecking -Global
            Initialize-InterclawEnvironment -RepoRoot $td
            Import-InterclawModule Core; Import-InterclawModule Deploy
            Initialize-AgentVolumes -WorkspaceRepos $wr -StackName $sn -SovereigntyTier $st -AgentConfigs $ac -TargetDir $td
        } -ArgumentList $InstallWorkspaceRepos, $script:StackName, $SovereigntyTier, $AgentConfigs, $TargetDir
        $volumeResult = $volumeJob | Wait-Job -Timeout $volumeTimeoutSec
        if (-not $volumeResult) {
            Stop-Job $volumeJob -ErrorAction SilentlyContinue -ErrorVariable volStopErr
            if ($volStopErr) { Write-SetupLog "Volume job stop reported errors: $($volStopErr[0].Exception.Message)" -Level WARN }
            $volumeOutput = Receive-Job $volumeJob -ErrorAction SilentlyContinue -ErrorVariable volRcvErr
            if ($null -ne $volumeOutput) { Write-Information -MessageData "  Partial output: $volumeOutput" -Tags "WARN" }
            if ($volRcvErr) { Write-SetupLog "Volume job receive reported errors: $($volRcvErr[0].Exception.Message)" -Level WARN }
            Remove-Job $volumeJob -ErrorAction SilentlyContinue -ErrorVariable volRmErr
            if ($volRmErr) { Write-SetupLog "Volume job remove reported errors: $($volRmErr[0].Exception.Message)" -Level WARN }
            Write-SetupLog "Initialize-AgentVolumes timed out after ${volumeTimeoutSec}s — parallel volume creation may have hung" -Level ERROR
            Write-Information -MessageData "  [FAIL] Volume initialization timed out after ${volumeTimeoutSec}s. Check Docker Desktop resource limits." -Tags "ERROR"
            throw "Initialize-AgentVolumes timed out after ${volumeTimeoutSec}s"
        }
        $volumeError = Receive-Job $volumeJob -ErrorAction SilentlyContinue -ErrorVariable volErr2
        if ($volErr2) { Write-SetupLog "Volume job receive (2) reported errors: $($volErr2[0].Exception.Message)" -Level WARN }
        Remove-Job $volumeJob -ErrorAction SilentlyContinue -ErrorVariable volRm2Err
        if ($volRm2Err) { Write-SetupLog "Volume job remove (2) reported errors: $($volRm2Err[0].Exception.Message)" -Level WARN }
        if ($null -ne $volumeError) {
            Write-SetupLog "Initialize-AgentVolumes errors: $volumeError" -Level WARN
        }
    }
    "Swarm" {
        Initialize-SwarmReadiness
        $swarmTimeoutSec = 300
        $resolvedStackName = if ($script:StackName) { $script:StackName } else { try { Get-StackName } catch { $ProjectCode } }
        $swarmJob = Start-Job -ScriptBlock {
            param($td, $ac, $pc, $sn, $its, $if, $iwr, $ia, $im, $st)
            $modulesDir = Join-Path $td "Skills" "Docker" "Modules"; $env:PSModulePath = "$modulesDir;$env:PSModulePath"
            Import-Module -Name (Join-Path $modulesDir "SalmonRun.ModuleLoader" "SalmonRun.ModuleLoader.psd1") -Force -DisableNameChecking -Global
            Initialize-InterclawEnvironment -RepoRoot $td
            Import-InterclawModule Core; Import-InterclawModule Deploy; Import-InterclawModule Fleet
            Publish-FleetStack -TargetDir $td -AgentConfigs $ac -ProjectCode $pc -StackName $sn -InstallTailscale $its -InstallFleet $if -InstallWorkspaceRepos $iwr -InstallBookkeeping $ia -InstallMarketer $im -SovereigntyTier $st
        } -ArgumentList $TargetDir, $AgentConfigs, $ProjectCode, $resolvedStackName, $InstallTailscale, $InstallFleet, $InstallWorkspaceRepos, $InstallBookkeeping, $InstallMarketer, $SovereigntyTier
        $swarmResult = $swarmJob | Wait-Job -Timeout $swarmTimeoutSec
        if (-not $swarmResult) {
            Stop-Job $swarmJob -ErrorAction SilentlyContinue -ErrorVariable swarmStopErr
            if ($swarmStopErr) { Write-SetupLog "Swarm job stop reported errors: $($swarmStopErr[0].Exception.Message)" -Level WARN }
            Remove-Job $swarmJob -ErrorAction SilentlyContinue -ErrorVariable swarmRmErr
            if ($swarmRmErr) { Write-SetupLog "Swarm job remove reported errors: $($swarmRmErr[0].Exception.Message)" -Level WARN }
            Write-SetupLog "Publish-FleetStack (Swarm phase) timed out after ${swarmTimeoutSec}s" -Level ERROR
            throw "Fleet stack publish (Swarm phase) timed out after ${swarmTimeoutSec}s"
        }
        $swarmError = Receive-Job $swarmJob -ErrorAction SilentlyContinue -ErrorVariable swarmErr2
        if ($swarmErr2) { Write-SetupLog "Swarm job receive (2) reported errors: $($swarmErr2[0].Exception.Message)" -Level WARN }
        Remove-Job $swarmJob -ErrorAction SilentlyContinue -ErrorVariable swarmRm2Err
        if ($swarmRm2Err) { Write-SetupLog "Swarm job remove (2) reported errors: $($swarmRm2Err[0].Exception.Message)" -Level WARN }
        if ($null -ne $swarmError) { Write-SetupLog "Publish-FleetStack errors: $swarmError" -Level WARN }
    }
    "Verify" {
        try { Test-FleetDeployment } catch { Write-Warning "Fleet deployment verification failed: $($_.Exception.Message)" }
    }
    "Aliases" {
        New-FleetAliases
    }
    "Compose" {
        $composePath = Join-Path $TargetDir "Infrastructure/docker-compose.interclaw.yml"
        New-FleetCompose -Agents $AgentConfigs -ProjectCode $ProjectCode -InstallTailscale $InstallTailscale -InstallFleet $InstallFleet -SovereigntyTier $SovereigntyTier -InstallBookkeeping $InstallBookkeeping -InstallMarketer $InstallMarketer -OutputPath $composePath
        Write-Information -MessageData "  [OK] Compose generated: $composePath" -Tags "INFO"
    }
    "Deploy" {
        Initialize-SwarmReadiness
        $deployTimeoutSec = 300
        $deployJob = Start-Job -ScriptBlock {
            param($td, $ac, $pc, $sn, $its, $if, $iwr, $ia, $im, $st)
            $modulesDir = Join-Path $td "Skills" "Docker" "Modules"; $env:PSModulePath = "$modulesDir;$env:PSModulePath"
            Import-Module -Name (Join-Path $modulesDir "SalmonRun.ModuleLoader" "SalmonRun.ModuleLoader.psd1") -Force -DisableNameChecking -Global
            Initialize-InterclawEnvironment -RepoRoot $td
            Import-InterclawModule Core; Import-InterclawModule Deploy; Import-InterclawModule Fleet
            Publish-FleetStack -TargetDir $td -AgentConfigs $ac -ProjectCode $pc -StackName $sn -InstallTailscale $its -InstallFleet $if -InstallWorkspaceRepos $iwr -InstallBookkeeping $ia -InstallMarketer $im -SovereigntyTier $st
        } -ArgumentList $TargetDir, $AgentConfigs, $ProjectCode, $script:StackName, $InstallTailscale, $InstallFleet, $InstallWorkspaceRepos, $InstallBookkeeping, $InstallMarketer, $SovereigntyTier
        $deployResult = $deployJob | Wait-Job -Timeout $deployTimeoutSec
        if (-not $deployResult) {
            Stop-Job $deployJob -ErrorAction SilentlyContinue -ErrorVariable depStopErr
            if ($depStopErr) { Write-SetupLog "Deploy job stop reported errors: $($depStopErr[0].Exception.Message)" -Level WARN }
            $deployOutput = Receive-Job $deployJob -ErrorAction SilentlyContinue -ErrorVariable depRcvErr
            if ($null -ne $deployOutput) { Write-Information -MessageData "  Partial output: $deployOutput" -Tags "WARN" }
            if ($depRcvErr) { Write-SetupLog "Deploy job receive reported errors: $($depRcvErr[0].Exception.Message)" -Level WARN }
            Remove-Job $deployJob -ErrorAction SilentlyContinue -ErrorVariable depRmErr
            if ($depRmErr) { Write-SetupLog "Deploy job remove reported errors: $($depRmErr[0].Exception.Message)" -Level WARN }
            Write-SetupLog "Publish-FleetStack timed out after ${deployTimeoutSec}s — docker stack deploy may have hung" -Level ERROR
            Write-Information -MessageData "  [FAIL] Stack deploy timed out after ${deployTimeoutSec}s. Check docker stack ps $($script:StackName) for hanging services." -Tags "ERROR"
            throw "Fleet stack deploy timed out after ${deployTimeoutSec}s"
        }
        $deployError = Receive-Job $deployJob -ErrorAction SilentlyContinue -ErrorVariable depErr2
        if ($depErr2) { Write-SetupLog "Deploy job receive (2) reported errors: $($depErr2[0].Exception.Message)" -Level WARN }
        Remove-Job $deployJob -ErrorAction SilentlyContinue -ErrorVariable depRm2Err
        if ($depRm2Err) { Write-SetupLog "Deploy job remove (2) reported errors: $($depRm2Err[0].Exception.Message)" -Level WARN }
        if ($null -ne $deployError) {
            Write-SetupLog "Publish-FleetStack errors: $deployError" -Level WARN
        }
        Test-FleetDeployment
    }
    "All" {
        Invoke-InterclawDeployment -TargetDir $TargetDir -AgentConfigs $AgentConfigs -ProjectCode $ProjectCode -InstallTailscale $InstallTailscale -InstallFleet $InstallFleet -InstallWorkspaceRepos $InstallWorkspaceRepos -InstallBookkeeping $InstallBookkeeping -InstallMarketer $InstallMarketer -SovereigntyTier $SovereigntyTier
    }
}


